name: Publish

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: yarn install
        run: yarn install
      - name: yarn deploy
        run: yarn deploy
